<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="UseCases\Categories\Interfaces\IUpdateCategory.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\comunication\comunication.csproj" />
    <ProjectReference Include="..\domain\domain.csproj" />
    <ProjectReference Include="..\infra\infra.csproj" />
  </ItemGroup>

</Project>
